# Site
name: 'Andronify'
description: 'Technical Blogs'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'bale.prashant1984@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    prashant:
      name:           prashant
      site:           https://www.andronify.com
      avatar:         ../assets/images/prashant.jpg
      bio:            "Hi, I am Prashant Bale, Traveller, Trekker, Nature Lover and Android Developer."
      email:          bale.prashant1984@gmail.com
      twitter:        https://twitter.com/prash_bale

    shraddha:
      name:           shraddha
      site:           https://www.andronify.com
      avatar:         ../assets/images/shraddha.jpg
      bio:            "Blogger, Shraddha Bale, love to explore new ideas and write on my morning coffee!"
      email:          scbagde@gmail.com
      twitter:        https://twitter.com/shraddhabagde
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: prashant
      avatar: /assets/images/prashant.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]